land_cover_lookup = {
    0: "Unknown",
    20: "Shrubs",
    30: "Herbaceous vegetation",
    40: "Cultivated and managed vegetation / agriculture",
    50: "Urban / built up",
    60: "Bare / sparse vegetation",
    70: "Snow and ice",
    80: "Permanent water bodies",
    90: "Herbaceous wetland",
    100: "Moss and lichen",
    111: "Closed forest, evergreen needle leaf",
    112: "Closed forest, evergreen broad leaf",
    113: "Closed forest, deciduous needle leaf",
    114: "Closed forest, deciduous broad leaf",
    115: "Closed forest, mixed",
    116: "Closed forest, not matching any of the other definitions",
    121: "Open forest, evergreen needle leaf",
    122: "Open forest, evergreen broad leaf",
    123: "Open forest, deciduous needle leaf",
    124: "Open forest, deciduous broad leaf",
    125: "Open forest, mixed",
    126: "Open forest, not matching any of the other definitions",
    200: "Oceans, seas"
}